services:
  shiny-app:
    build: .
    container_name: nobel-shiny-app
    restart: always
    ports:
      - "3838:3838"
    volumes:
      - ./app.R:/srv/shiny-server/app.R
      - ./nobel.csv:/srv/shiny-server/nobel.csv
